use anyhow::Result;
use serde::{Deserialize, Serialize};

#[derive(Clone)]
pub struct AnthropicAdapter {
    model: String,
}

impl AnthropicAdapter {
    pub fn new(model: String) -> Self {
        Self { model }
    }

    pub async fn plan(&self, prompt: &str) -> Result<String> {
        Ok(format!("[{}] Plan generated for: {}", self.model, prompt))
    }

    pub async fn review(&self, code: &str) -> Result<ReviewOutput> {
        Ok(ReviewOutput {
            summary: format!("Reviewed by {}", self.model),
            issues: vec![],
            code: code.to_string(),
        })
    }
}

#[derive(Clone)]
pub struct OllamaAdapter {
    model: String,
}

impl OllamaAdapter {
    pub fn new(model: String) -> Self {
        Self { model }
    }

    pub async fn code(&self, plan: &str) -> Result<String> {
        Ok(format!("// generated by {}\n{}", self.model, plan))
    }
}

#[derive(Clone)]
pub struct GitAdapter {
    repo_root: String,
    branch: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct CommitOutput {
    pub sha: String,
    pub branch: String,
}

impl GitAdapter {
    pub fn new(repo_root: String, branch: String) -> Self {
        Self { repo_root, branch }
    }

    pub async fn commit(
        &self,
        job_id: &str,
        title: &str,
        files: &[String],
        summary: &str,
    ) -> Result<CommitOutput> {
        let _ = (&self.repo_root, title, files, summary);
        Ok(CommitOutput {
            sha: format!("{}-mock-sha", &job_id[..8.min(job_id.len())]),
            branch: self.branch.clone(),
        })
    }
}

#[derive(Clone)]
pub struct LinearAdapter;

impl LinearAdapter {
    pub async fn update_issue_state(&self, _issue_id: &str, _state: &str) -> Result<()> {
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ReviewIssue {
    pub severity: String,
    pub message: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ReviewOutput {
    pub summary: String,
    pub issues: Vec<ReviewIssue>,
    pub code: String,
}
